In [2]:
import numpy as np

## Создание массивов numpy

In [3]:
data=np.array([1,2,3]) #Создааём массив numpy
print(data)
print(data.max())

[1 2 3]
3


In [4]:
np.ones(3)
np.zeros(3)
np.random.random(3)

array([0.47919577, 0.9604483 , 0.55743211])

## Арифметические операции над массивами NumPy

In [5]:
data = np.array([1,2]) #создаём первый массив
ones = np.ones(2) #создаём второй массив
data+ones
#можно использовать /-деление *-умножение +суммирование -вычитание

array([2., 3.])

In [6]:
#опреации с массивом и одним числом
#на число умножааются все элементы массива
data*1.6

array([1.6, 3.2])

## Индексация массива NumPy 

In [7]:
#получение элементов и участков массивов
data=np.array([1,2,3])
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])

1
2
[1 2]
[2 3]


## Агрегирование в NumPy

In [8]:
print(data.max()) #поиск максимального значения
print(data.min()) #поиск минимального значения
print(data.sum()) #поиск сумма элементов массива

print(data.mean()) #поиск среднее арифметическое
print(data.prod()) #поиск перемножение всех элементов
print(data.std())  #поиск расчёт среднеквадратического отклонения

3
1
6
2.0
6
0.816496580927726


## Создание матриц 

In [9]:
print(np.array([[1,2],[3,4]]))
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.70128742 0.37477447]
 [0.2153706  0.26586748]
 [0.3890011  0.49435795]]


## Арифметические операции над матрицами NumPy

In [10]:
#сложение матриц
data=np.array([[1,2],[3,4]])
ones=np.ones((2,2))
data+ones

array([[2., 3.],
       [4., 5.]])

In [11]:
#сложение матрицы и вектора с применение трансляции
ones_raw=np.ones(2)
data+ones_raw
# В других случаях рамерности матриц должны быть одинаковыми

array([[2., 3.],
       [4., 5.]])

## dot() Скалярное произведение

In [12]:
data=np.array([1,2,3])
powers_of_ten=np.array([[1,10],[100,1000],[10000,100000]])
print(powers_of_ten)
data.dot(powers_of_ten)

[[     1     10]
 [   100   1000]
 [ 10000 100000]]


array([ 30201, 302010])

In [13]:
#Индексация матрицы
data=np.array([[1,2],[3,4],[5,6]])
print(data)
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


In [ ]:
#Агрегирование аналогично векторам
#но можно примениять отдельно к строками и столбцам
print(data.max(axis=0))
print(data.max(axis=1))

## Транспонирование и изменение формы матриц в numpy

In [22]:
print(data)
print(data.T) #Транспонирование матрицы

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [ ]:
#метод reshape
data=np.array([1,2,3,4,5,6])
print(data)

data.reshape(2,3)
print(data)

data.reshape(3,2)
print(data)

## Трёхмерные массивы 

In [16]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#задание трёхмерного массива вручную
print(a)
print(np.ones((4,3,2)))
print(np.zeros((4,3,2)))
print(np.random.random((4,3,2)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0.86656363 0.43909541]
  [0.35772762 0.79353271]
  [0.93367058 0.25064902]]

 [[0.18861037 0.50551684]
  [0.99640887 0.11561758]
  [0.17390407 0.76389529]]

 [[0.36283683 0.85846916]
  [0.68823355 0.58946942]
  [0.86091253 0.7850608 ]]

 [[0.04577812 0.37534406]
  [0.06133116 0.56001282]
  [0.77685291 0.16143764]]]


## Примеры

In [17]:
#Реализация формулы среднеквадратичной ошибки
predictions=np.array([1,1,1])
labels=np.array([1,2,3])

n=3 #количество элементов вектора
error=(1/n)*np.sum(np.square(predictions-labels))
print(error)

1.6666666666666665
